apiVersion: v1
kind: ConfigMap
metadata:
  name: autoserve-config
data:
  db-url: "jdbc:sqlserver://db-service:1433;databaseName=autoserve"
---
apiVersion: v1
kind: Secret
metadata:
  name: autoserve-secret
type: Opaque
data:
  db-username: c2E=  # base64 of 'sa'
  db-password: WW91clBhc3N3b3JkMTIz  # base64 of 'YourPassword123'
  sa-password: WW91clBhc3N3b3JkMTIz