
spring:
  profiles:
    active: dev
  config:
    # Load variables from .env if present (no error if missing)
    import: optional:file:.env[.properties]

server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:


    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  websocket:
    enabled: true

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

sendgrid:
  api:
    key: ${SENDGRID_API_KEY}
  from:
    email: ${SENDGRID_FROM_EMAIL}


---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

sendgrid:
  api:
    key: ${SENDGRID_API_KEY}
  from:
    email: ${SENDGRID_FROM_EMAIL}

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        globally_quoted_identifiers: true

sendgrid:
  api:
    key: test-api-key
  from:
    email: test@autoserve.com