
spring:
  profiles:
    active: test

server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:gearupdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  h2:
    console:
      enabled: true

jwt:
  secret: devSecretKeyForJwtTokenGenerationThatShouldBeAtLeast256BitsLongForDevelopment
  expiration: 86400000

sendgrid:
  api:
    key: SG.test-api-key
  from:
    email: dev@gearup.com

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

sendgrid:
  api:
    key: ${SENDGRID_API_KEY}
  from:
    email: ${SENDGRID_FROM_EMAIL}

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        globally_quoted_identifiers: true

jwt:
  secret: testSecretKeyForJwtTokenGenerationThatShouldBeAtLeast256BitsLong
  expiration: 86400000

sendgrid:
  api:
    key: test-api-key
  from:
    email: test@autoserve.com